spring:
  datasource:
    url: jdbc:postgresql://172.2.0.21:5435/test_placeid_generate
    username: test_waq
    password: wayzpg_waq
    driver-class-name: org.postgresql.Driver
    maxActive: 50
    initialSize: 10
    maxWait: 60000
    minIdle: 6
    timeBetweenEvictionRunsMillis: 60000
    minEvictableIdleTimeMillis: 300000
    validationQuery: select 'x'
    testWhileIdle: true
    testOnBorrow: false
    testOnReturn: false
    poolPreparedStatements: true
    maxOpenPreparedStatements: 20